hover effects in your navbar change by awais alam
bilalahmad99/bilalahmad99.github.io pull request #1
Opened 2022-02-28 16:33 UTC by awaisalam909

check then merge

2022-03-17 21:40 UTC, bilalahmad99 commented on _sass/jekyll-theme-modernist.scss
> +          color:red;
can we make colour a bit more suitable with the theme, e.g. grey, blue etc

2022-03-17 21:41 UTC, bilalahmad99 requested changes
change hover color to be suitable to theme

2022-04-25 22:10 UTC, closed without merging

2022-04-25 22:28 UTC, awaisalam909 commented
bilal bhai wo docker wala idea add kr dy kindly

On Tue, Apr 26, 2022, 3:11 AM Bilal Ahmad ***@***.***> wrote:

> Closed #1 <https://github.com/bilalahmad99/bilalahmad99.github.io/pull/1>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bilalahmad99/bilalahmad99.github.io/pull/1#event-6493924255>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4WKQU577ZEJVIRCUTTGWDVG4J7LANCNFSM5PRSMUAA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-10-11 08:09 UTC, awaisalam909 commented
ok I customz better colors

On Fri, Mar 18, 2022, 2:41 AM Bilal Ahmad ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> change hover color to be suitable to theme
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bilalahmad99/bilalahmad99.github.io/pull/1#pullrequestreview-913739273>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4WKQU32P3X23R3MSRSSVDVAORH7ANCNFSM5PRSMUAA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>