put  the link in archive pulumi vs terroform vs AWS CDK same error
bilalahmad99/bilalahmad99.github.io pull request #3
Opened 2022-03-07 13:47 UTC by awaisalam909

2022-03-17 21:39 UTC, bilalahmad99 requested changes

2022-03-17 21:39 UTC, bilalahmad99 commented on pages/archive.md
> +[https://www.pulumi.com/registry/](https://www.pulumi.com/registry/).
why is this link required?

2022-03-17 21:44 UTC, awaisalam909 commented
because you a add saquare brakt extra in this link  thats why I change and
remove the saqure

On Fri, Mar 18, 2022, 2:39 AM Bilal Ahmad ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In pages/archive.md
> <https://github.com/bilalahmad99/bilalahmad99.github.io/pull/3#discussion_r829533712>
> :
>
> > @@ -10,6 +10,9 @@ layout: default
>  [Pulumi vs Terroform vs AWS CDK](./pulumi.html)<br>
>  <sub><sup>_[Infrastructure-as-a-code]_ **7 min read**</sup></sub>
>
> +[https://www.pulumi.com/registry/](https://www.pulumi.com/registry/).
>
> why is this link required?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bilalahmad99/bilalahmad99.github.io/pull/3#pullrequestreview-913737530>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4WKQXC3MSNDVKDRTNDFITVAORABANCNFSM5QDLAX2Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-25 22:12 UTC, bilalahmad99 requested changes
outdated, closing the PR

2022-04-25 22:12 UTC, closed without merging